// Generated by CoffeeScript 1.8.0
(function() {
  var Bacon, ModelBacon, bjq, expect, model, twice;

  expect = require("chai").expect;

  bjq = require("../src/bacon-dom");

  twice = function(x) {
    return x * 2;
  };

  Bacon = require("baconjs");

  ModelBacon = require("bacon.model");

  model = Bacon.Model;

  describe("Node.js specific", function() {
    it("exports original Bacon.$", function() {
      return expect(bjq).to.equal(Bacon.$);
    });
    return it("shares the same bacon with model", function() {
      return expect(bjq).to.equal(ModelBacon.$);
    });
  });

}).call(this);

//# sourceMappingURL=bacon-dom.spec.js.map
