// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      clean: {
        dist: ["dist/"],
        coffee: ["dist/*.coffee"]
      },
      coffee: {
        compile: {
          files: [
            {
              "dist/bacon.query.js": "src/*.coffee"
            }
          ]
        }
      },
      uglify: {
        dist: {
          src: "dist/*.js",
          dest: "dist/*.min.js"
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-coffee");
    grunt.loadNpmTasks("grunt-contrib-clean");
    grunt.loadNpmTasks("grunt-contrib-uglify");
    grunt.registerTask("build", ["clean:dist", "coffee", "uglify", "clean:coffee"]);
    return grunt.registerTask("default", ["build"]);
  };

}).call(this);

//# sourceMappingURL=Gruntfile.js.map
